name = "portfolio-cdn"
main = "cloudflare-worker.js"
compatibility_date = "2025-09-16"

[build]
command = ""

[vars]
SKIP_DEPENDENCY_INSTALL = "true"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "portfolio-cdn"

[[kv_namespaces]]
binding = "KV"
id = "e0f69c917c914d5ea809ee717f4a4942"
