name = "portfolio-cdn"
main = "cloudflare-worker.js"
compatibility_date = "2025-09-16"

[build]
command = ""

[vars]
SKIP_DEPENDENCY_INSTALL = "true"
R2_BUCKET_PUBLIC_URL = "assets.maxemitchell.com"

[[kv_namespaces]]
binding = "KV"
id = "e0f69c917c914d5ea809ee717f4a4942"

[[routes]]
pattern = "cdn.maxemitchell.com"
custom_domain = true

[observability]
enabled = true
